name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.x

      - name: Install dependencies
        run: sudo npm install

      - name: Run CI checks
        env:
          CI: true
        run: npm run ci
