name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        run: echo NODE_VERSION=$(cat .node-version) >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run CI checks
        run: npm run ci
